language: node_js

sudo: true

node_js:
    - 8

services:
    - xvfb

before_install:
    - export CHROME_BIN=chromium-browser

script: gulp default --ci

branches:
    only:
      - master

addons:
    firefox: latest
